project_id = "dnntsdncmptuxctbcjsp"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-presentation]
verify_jwt = false

[functions.migrate-tokens]
verify_jwt = false

[functions.generate-course]
verify_jwt = false
